# -*- coding: utf-8 -*-
# 해석 팝업(_kor1) · 전체 듣기 팝업(_all) 의 kr 줄 배치
# read_measure.py 가 재서 쓴 값입니다. 손대지 마세요.
KR = {
 'p140_02': [
  "빨간 자전거",
  "Leo는 늘 자전거를 갖는 것을 꿈꿔 왔었다.",
  "그의 꿈을 이루기 위해<span style='left:-866px'>그는 돈을 모으며 2년을 보냈다.</span>",
  "그는<span style='left:-1060px'>잔디를 깎거나 낙엽을 줍는 것 같은 이웃들을 위한 작은 일들을 했다.</span>",
  "마침내 Leo는 완벽한 자전거를 살 수 있었다.",
  "그것은 18단 기어가 달린 밝은 빨간색 자전거였다.",
  "그는 그것에 Big<span style='left:-869px'>Red라는<span style='left:0px'>이름을 붙였다.</span></span>",
  "그는 어디를 가든 Big Red를 타고 다녔다.",
  "그가 그것을 많이 타면 탈수록<span style='left:-556px'>그는 더 많은 추억을<span style='left:-216px'>만들었다.</span></span>",
  "그가 키가 커지자 Big Red는 그에게 너무<span style='left:-445px'>작아졌다.</span>",
  "그것은 여전히 좋은 상태였지만, Leo는 새<span style='left:-530px'>자전거를 탈 때가 되었다는 것을 알았다.</span>",
  "Leo는 도움이 필요한 사람들에게 자전거를 보내는 것이 임무인 단체에 Big Red를<span style='left:-20px'>기부하기로 결심했다.</span>",
  "하지만 우선<span style='left:-910px'>Leo는 Big Red를 최고의 상태로 보이게 만들고 싶었다.</span>",
  "그는 그것을 깨끗이 닦고,<span style='left:-768px'>체인에 기름을 바르고, 손잡이를 교체했다.</span>",
  "그는 “모든 모험에 대해<span style='left:-809px'>고마워.”라고 속삭였다.</span>",
  "무거운 마음으로 그는 Big Red를<span style='left:-707px'>운송 컨테이너까지 타고 갔다.</span>",
  "문이 닫힐 때 그는 작별<span style='left:-800px'>인사를 했다.</span>",
 ],
 'p141_01': [
  "Big Red는 새로운 나라로 이동했다.",
  "그것은 Emily와 함께 하는<span style='left:-723px'>새로운 집을 찾았는데, Emily는 할머니와 함께 살며 밭일을 도왔다.</span>",
  "Big Red 덕분에 Emily는 밭에서 새를 쫓기 위해 자전거를<span style='left:-338px'>타고 물건을 팔러 시장에 갈 수 있었다.</span>",
  "그녀는 또한 매일 Big Red를 타고 학교에 갔다.",
  "그러나<span style='left:-1088px'>무엇보다 자전거를 타는 것은 그녀에게 조용한 기쁨을 주었다.</span>",
  "그녀는 바람이 얼굴을 스치는 것을 느꼈고 더 넓은 세상을 꿈꾸기 시작했다.",
  "그러던 어느 날, Emily는 큰 도시의 학교에서 공부를 계속할 기회를 얻게 되었다.",
  "그녀는 Big Red와의 여정이 끝났음을<span style='left:-642px'>알았다.</span>",
  "그녀는 그것이 정말로 그것을 필요로<span style='left:-683px'>하는 누군가에게 가기를 바랐다.</span>",
 ],
 'p142_01': [
  "어느 날 아침, Emily는 라디오에서 뉴스 보도를 들었다.",
  "한 지역 병원에서 보건 의료 종사자들이 아픈 사람들을 방문하기 위해 자전거가 필요했다.",
  "Emily는 Big Red를 바라보며 미소 지었다.",
  "그녀는<span style='left:-975px'>무엇을 해야<span style='left:0px'>할지 알았다.</span></span>",
  "그날 오후, 그녀는 Big Red를 병원에 제공했고 그것이 다른 사람들을<span style='left:-50px'>계속 돕게 된 것이 자랑스러웠다.</span>",
  "그녀는 자전거의 안장을 토닥거리며 “모든 것에 고마워.”라고 속삭였다.",
  "병원에서 자전거는 트레일러를 달아 구급차로 바뀌었다.",
  "트레일러에는 환자들을 이동 중에 안전하게 지켜기 위해 들것과<span style='left:-328px'>안전벨트가 있었다.</span>",
  "Big<span style='left:-1014px'>Red는 일할 준비가 되었다.</span>",
 ],
 'p143_01': [
  "Hannah라는 이름의 보건 의료 종사자가 그 자전거를 사용하기 시작했다.",
  "그녀는 약을 배달하고 환자들을 병원으로 데려오며 자동차가 갈 수<span style='left:-306px'>없는 좁은 길을 따라 Big Red를 달렸다.</span>",
  "곧 그것은 그것의 좋은 일로 유명해졌고, 마을 사람들은<span style='left:-438px'>그것을 매우 좋아했다.</span>",
  "Hannah가 다른 마을에서 새 역할을 맡게 되었을 때, 그녀는 마지막으로 Big Red를<span style='left:-20px'>탔다.</span>",
  "그녀는 그것의 여정이 어디서 처음<span style='left:-611px'>시작되었는지<span style='left:0px'>궁금해하며 “고마워.”라고 속삭였다.</span></span>",
  "해석x",
  "한<span style='left:-547px'>소녀가 한때 그것을 시장에 타고 갔다는 흔적 또는<span style='left:-489px'>한 소년이 작은 마을을 돌아다녔다는 흔적도 없었다.</span></span>",
  "그러나 그들은 Big<span style='left:-907px'>Red를 기억했고, Hannah 역시 그럴 것이다.</span>",
  "해석x",
  "해석x",
 ],
}
